# Generated by Django 5.0 on 2026-03-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20260320_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='category',
        ),
        migrations.AddField(
            model_name='todotask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todo.category'),
        ),
    ]
